spring.application.name=app.pos
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Security configurations
security.jwt.secret=${JWT_SECRET:9a2f34af8b302c340b12e345f67a89bc23d45e6789f01ab23cd45ef6789a01bc}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}
security.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}
security.jwt.cookie-name=${JWT_COOKIE_NAME:jwt_token}
security.jwt.refresh-cookie-name=${JWT_REFRESH_COOKIE_NAME:refresh_token}
security.jwt.cookie-secure=${JWT_COOKIE_SECURE:false}
security.jwt.cookie-same-site=${JWT_COOKIE_SAME_SITE:Strict}

# Billing Provider Strategy (factus, mock, siigo, etc.)
billing.provider=${BILLING_PROVIDER:factus}

# Factus API Configuration
factus.url=${FACTUS_URL:https://api-sandbox.factus.com.co}

factus.client-id=${FACTUS_CLIENT_ID:a16096d5-3edb-4891-81f6-a86d7039a852}
factus.client-secret=${FACTUS_CLIENT_SECRET:HPFZf80uFczrWtemDtrQvtmOcUJ2DeetFQsioPkL}
factus.username=${FACTUS_USERNAME:sandbox@factus.com.co}
factus.password=${FACTUS_PASSWORD:sandbox2024%}
factus.numbering-range-id=${FACTUS_NUMBERING_RANGE_ID:8}

# SpringDoc / Swagger UI configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.deep-linking=true
springdoc.swagger-ui.display-operation-id=false
springdoc.swagger-ui.default-models-expand-depth=2
springdoc.swagger-ui.default-model-expand-depth=2
springdoc.swagger-ui.doc-expansion=none
